import { Minus, Plus, ShoppingBag, Trash2 } from 'lucide-react';
import { useCart } from '../../context/CartContext';
import { navigate } from '../../utils/navigation';
import styles from './MiniCart.module.css';
const money = (value) => new Intl.NumberFormat('es-CO', { style: 'currency', currency: 'COP', maximumFractionDigits: 0 }).format(value);
export function MiniCart({ open, onClose }) {
  const { items, subtotal, removeItem, updateQuantity } = useCart();
  const visibleItems = items.slice(0, 5);
  const remaining = items.length - visibleItems.length;
  const openCart = () => { navigate('/carrito'); onClose(); };
  return <section className={`${styles.panel} ${open ? styles.open : ''}`} aria-label="Resumen del carrito" aria-hidden={!open}><h2>Tu carrito</h2>{!items.length ? <div className={styles.empty}><ShoppingBag size={31} /><p>Tu carrito está vacío</p><a href="/tienda" onClick={onClose}>Explorar tienda</a></div> : <><div className={styles.items}>{visibleItems.map(({ product, quantity }) => <article key={`${product.id}-${product.variantId || 'base'}`}><img src={product.image} alt={product.name} /><div><b>{product.name}</b>{product.selectedVariant && <small>{Object.values(product.selectedVariant).join(' · ')}</small>}<span>{money(product.price)}</span><nav aria-label={`Cantidad de ${product.name}`}><button type="button" aria-label="Reducir cantidad" disabled={quantity === 1} onClick={() => updateQuantity(product.id, quantity - 1, product.variantId || null)}><Minus size={12} /></button><small>{quantity}</small><button type="button" aria-label="Aumentar cantidad" disabled={quantity >= (product.stock ?? Infinity)} onClick={() => updateQuantity(product.id, quantity + 1, product.variantId || null)}><Plus size={12} /></button></nav></div><button className={styles.remove} type="button" aria-label={`Eliminar ${product.name}`} onClick={() => removeItem(product.id, product.variantId || null)}><Trash2 size={16} /></button></article>)}</div>{remaining > 0 && <p className={styles.more}>Hay {remaining} {remaining === 1 ? 'producto adicional' : 'productos adicionales'} en tu carrito.</p>}<div className={styles.total}><span>Subtotal</span><strong>{money(subtotal)}</strong></div><footer><button type="button" className={styles.view} onClick={openCart}>Ver carrito</button><button className={styles.checkout} type="button" onClick={() => { navigate('/checkout'); onClose(); }}>Checkout</button></footer></>}</section>;
}
