import { useEffect, useState } from 'react';
import { Heart, MapPin, Package, Pencil, Scale, UserRound } from 'lucide-react';
import { StoreBanner } from '../components/StoreBanner';
import { useAuth } from '../context/AuthContext';
import styles from './AccountPage.module.css';

const go = (hash) => { window.location.hash = hash; window.scrollTo({ top: 0, behavior: 'smooth' }); };
const money = (value) => new Intl.NumberFormat('es-CO', { style: 'currency', currency: 'COP', maximumFractionDigits: 0 }).format(Number(value));

export function AccountPage() {
  const { user, request, setUser, logout } = useAuth();
  const [values, setValues] = useState(user || {});
  const [state, setState] = useState('idle');
  useEffect(() => setValues(user || {}), [user]);
  const save = async (event) => { event.preventDefault(); setState('loading'); try { const data = await request('/account/profile', { method: 'PUT', body: JSON.stringify(values) }); setUser(data.user); setState('success'); } catch { setState('error'); } };
  const cards = [{ label: 'Mis pedidos', text: 'Consulta el estado y detalle de tus compras.', icon: Package, hash: 'mis-pedidos' }, { label: 'Mis direcciones', text: 'Administra tus direcciones de entrega.', icon: MapPin, hash: 'mis-direcciones' }, { label: 'Mis favoritos', text: 'Revisa los productos que guardaste.', icon: Heart, hash: 'favoritos' }, { label: 'Comparar productos', text: 'Compara tus productos seleccionados.', icon: Scale, hash: 'comparar' }];
  return <main className={styles.page}><StoreBanner title="Mi cuenta" items={['Inicio', 'Mi cuenta']} /><section className={styles.content}><header className={styles.welcome}><span><UserRound size={22} /></span><div><p>Hola, {user?.name}</p><h2>Gestiona tu cuenta</h2></div></header><div className={styles.layout}><form className={styles.profile} onSubmit={save}><header><div><h3>Información personal</h3><p>Mantén tus datos actualizados.</p></div><Pencil size={18} /></header><div className={styles.fields}>{[['Nombre','name'],['Apellido','lastName'],['Correo electrónico','email'],['Teléfono','phone']].map(([label, name]) => <label key={name}>{label}<input required type={name === 'email' ? 'email' : 'text'} value={values[name] || ''} onChange={(e) => setValues({ ...values, [name]: e.target.value })} /></label>)}</div>{state === 'success' && <p className={styles.success}>Tus datos fueron actualizados.</p>}{state === 'error' && <p className={styles.error}>No fue posible actualizar tus datos.</p>}<button disabled={state === 'loading'}>{state === 'loading' ? 'Guardando...' : 'Guardar cambios'}</button></form><aside className={styles.actions}>{cards.map(({ label, text, icon: Icon, hash }) => <button key={hash} onClick={() => go(hash)}><Icon size={21} /><span><b>{label}</b><small>{text}</small></span></button>)}<button className={styles.logout} onClick={async () => { await logout(); go('login'); }}>Cerrar sesión</button></aside></div></section></main>;
}

export function OrdersPage() {
  const { request } = useAuth(); const [orders, setOrders] = useState(null); const [error, setError] = useState('');
  useEffect(() => { request('/orders').then((data) => setOrders(data.orders)).catch((e) => setError(e.message)); }, [request]);
  return <main className={styles.page}><StoreBanner title="Mis pedidos" items={['Inicio', 'Mi cuenta', 'Mis pedidos']} /><section className={styles.content}><button className={styles.back} onClick={() => go('cuenta')}>← Volver a mi cuenta</button><h2 className={styles.title}>Historial de pedidos</h2>{error && <p className={styles.error}>{error}</p>}{orders === null ? <p>Cargando pedidos...</p> : !orders.length ? <div className={styles.empty}><Package size={42} /><h3>Aún no tienes pedidos</h3><p>Cuando realices una compra, podrás verla aquí.</p><button onClick={() => go('tienda')}>Ir a la tienda</button></div> : <div className={styles.orders}>{orders.map((order) => <article key={order.id}><div><b>Pedido #{order.publicNumber}</b><small>{new Date(order.createdAt).toLocaleDateString('es-CO')}</small></div><span>{order.status.replaceAll('_', ' ')}</span><strong>{money(order.grandTotal)}</strong><button onClick={() => go('mis-pedidos/' + order.id)}>Ver detalle</button></article>)}</div>}</section></main>;
}

export function AddressesPage() {
  const { request } = useAuth(); const [addresses, setAddresses] = useState(null); const [form, setForm] = useState(null); const [error, setError] = useState('');
  const load = () => request('/account/addresses').then((data) => setAddresses(data.addresses)).catch((e) => setError(e.message));
  useEffect(load, [request]);
  const save = async (event) => { event.preventDefault(); try { await request(form.id ? '/account/addresses/' + form.id : '/account/addresses', { method: form.id ? 'PUT' : 'POST', body: JSON.stringify(form) }); setForm(null); load(); } catch (e) { setError(e.message); } };
  return <main className={styles.page}><StoreBanner title="Mis direcciones" items={['Inicio', 'Mi cuenta', 'Mis direcciones']} /><section className={styles.content}><button className={styles.back} onClick={() => go('cuenta')}>← Volver a mi cuenta</button><div className={styles.sectionHeader}><h2 className={styles.title}>Direcciones de entrega</h2><button onClick={() => setForm({ countryCode: 'CO', isDefault: !addresses?.length })}>Agregar dirección</button></div>{error && <p className={styles.error}>{error}</p>}{addresses === null ? <p>Cargando direcciones...</p> : !addresses.length && !form ? <div className={styles.empty}><MapPin size={42} /><h3>No tienes direcciones guardadas</h3><p>Agrega una dirección para agilizar tus próximas compras.</p></div> : <div className={styles.addresses}>{addresses.map((address) => <article key={address.id}><b>{address.recipientName}{address.isDefault && <span>Principal</span>}</b><p>{address.addressLine1}{address.addressLine2 ? ', ' + address.addressLine2 : ''}<br />{address.city}, {address.region}<br />{address.phone}</p><div><button onClick={() => setForm(address)}>Editar</button><button onClick={async () => { await request('/account/addresses/' + address.id, { method: 'DELETE' }); load(); }}>Eliminar</button></div></article>)}</div>}{form && <form className={styles.addressForm} onSubmit={save}><h3>{form.id ? 'Editar dirección' : 'Nueva dirección'}</h3>{[['Nombre de quien recibe','recipientName'],['Teléfono','phone'],['Departamento','region'],['Ciudad','city'],['Dirección','addressLine1'],['Complemento (opcional)','addressLine2'],['Referencia (opcional)','reference']].map(([label, key]) => <label key={key}>{label}<input required={!label.includes('opcional')} value={form[key] || ''} onChange={(e) => setForm({ ...form, [key]: e.target.value })} /></label>)}<label className={styles.default}><input type="checkbox" checked={Boolean(form.isDefault)} onChange={(e) => setForm({ ...form, isDefault: e.target.checked })} />Usar como dirección principal</label><div><button type="button" onClick={() => setForm(null)}>Cancelar</button><button>Guardar dirección</button></div></form>}</section></main>;
}
export function OrderDetailPage() {
  const { request } = useAuth();
  const id = window.location.hash.replace('#mis-pedidos/', '').split('?')[0];
  const [order, setOrder] = useState(null);
  const [error, setError] = useState('');
  useEffect(() => { request('/orders/' + id).then((data) => setOrder(data.order)).catch((e) => setError(e.message)); }, [id, request]);
  return <main className={styles.page}><StoreBanner title="Detalle del pedido" items={['Inicio', 'Mi cuenta', 'Mis pedidos', 'Detalle']} /><section className={styles.content}><button className={styles.back} onClick={() => go('mis-pedidos')}>← Volver a mis pedidos</button>{error && <p className={styles.error}>{error}</p>}{!order ? <p>Cargando pedido...</p> : <section className={styles.detail}><header><div><small>Pedido</small><h2>#{order.publicNumber}</h2></div><span>{order.status.replaceAll('_', ' ')}</span></header><p>Realizado el {new Date(order.createdAt).toLocaleDateString('es-CO')}</p><div className={styles.detailItems}>{order.items.map((item) => <article key={item.id}><span>{item.quantity}×</span><b>{item.nameSnapshot}</b><strong>{money(item.lineTotal)}</strong></article>)}</div><dl><div><dt>Subtotal</dt><dd>{money(order.subtotal)}</dd></div><div><dt>Envío</dt><dd>{money(order.shippingTotal)}</dd></div><div className={styles.grandTotal}><dt>Total</dt><dd>{money(order.grandTotal)}</dd></div></dl></section>}</section></main>;
}