import { FormEvent, useState } from 'react';
import { CreditCard, LockKeyhole, PackageCheck, ShieldCheck, ShoppingBag } from 'lucide-react';
import { useCart } from '../context/CartContext';
import styles from './CheckoutPage.module.css';

const money = (value: number) => new Intl.NumberFormat('es-CO', { style: 'currency', currency: 'COP', maximumFractionDigits: 0 }).format(value);
export function CheckoutPage() {
  const { items, subtotal } = useCart() as any;
  const [complete, setComplete] = useState(false);
  const [department, setDepartment] = useState(() => { const saved = window.localStorage.getItem('fefcomputer-location'); return saved === 'Selecciona tu departamento' ? '' : (saved || ''); });
  const departments = ['Amazonas', 'Antioquia', 'Arauca', 'Atlantico', 'Bolivar', 'Boyaca', 'Caldas', 'Caqueta', 'Casanare', 'Cauca', 'Cesar', 'Choco', 'Cordoba', 'Cundinamarca', 'Guainia', 'Guaviare', 'Huila', 'La Guajira', 'Magdalena', 'Meta', 'Narino', 'Norte de Santander', 'Putumayo', 'Quindio', 'Risaralda', 'San Andres, Providencia y Santa Catalina', 'Santander', 'Sucre', 'Tolima', 'Valle del Cauca', 'Vaupes', 'Vichada'];
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setComplete(true); };
  if (!items.length) return <main className={styles.page}><section className={styles.empty}><ShoppingBag size={48} /><h1>Tu carrito está vacío</h1><p>Agrega productos para finalizar tu compra.</p><a href="/tienda">Ir a la tienda</a></section></main>;
  if (complete) return <main className={styles.page}><section className={styles.empty} role="status"><PackageCheck size={48} /><h1>¡Pedido listo para confirmar!</h1><p>Hemos recibido tus datos. La integración de pago estará disponible próximamente.</p><a href="/tienda">Seguir comprando</a></section></main>;
  return <main className={styles.page}><header className={styles.heading}><span><LockKeyhole size={15} />Compra segura</span><h1>Finalizar compra</h1><p>Completa tus datos para revisar y confirmar tu pedido.</p></header><form className={styles.layout} onSubmit={submit}><section className={styles.card}><header><div><h2>Información de entrega</h2><p>Usaremos estos datos para contactarte y enviar tu pedido.</p></div><span><ShieldCheck size={16} />Datos protegidos</span></header><div className={styles.fields}><label>Nombre completo<input required autoComplete="name" placeholder="Escribe tu nombre completo" /></label><label>Correo electrónico<input required type="email" autoComplete="email" placeholder="nombre@ejemplo.com" /></label><label>Teléfono<input required type="tel" autoComplete="tel" placeholder="300 000 0000" /></label><label>Ciudad<input required autoComplete="address-level2" placeholder="Tu ciudad" /></label><label className={styles.wide}>Dirección<input required autoComplete="street-address" placeholder="Calle, carrera, número, apartamento" /></label><label>Departamento<select required value={department} onChange={(event) => setDepartment(event.target.value)}><option value="" disabled>Selecciona una opción</option>{departments.map((item) => <option key={item} value={item}>{item}</option>)}</select></label><label>Código postal <em>(opcional)</em><input autoComplete="postal-code" placeholder="Código postal" /></label><label className={styles.wide}>Notas del pedido <em>(opcional)</em><textarea placeholder="Indicaciones de entrega o información adicional" /></label></div></section><aside className={styles.side}><section className={styles.card}><div className={styles.title}><h2>Resumen del pedido</h2><a href="/carrito">Editar carrito</a></div><ul>{items.map(({ product, quantity }: any) => <li key={product.id}><img src={product.image} alt={product.name} /><span><b>{product.name}</b><small>Cantidad: {quantity}</small></span><strong>{money(product.price * quantity)}</strong></li>)}</ul><dl><div><dt>Subtotal</dt><dd>{money(subtotal)}</dd></div><div><dt>Envío</dt><dd className={styles.free}>Gratis</dd></div><div className={styles.total}><dt>Total</dt><dd>{money(subtotal)}</dd></div></dl></section><fieldset className={styles.card}><strong>Método de pago</strong><p>Selecciona cómo deseas continuar.</p><label className={styles.payment}><input type="radio" name="payment" defaultChecked /><CreditCard size={19} /><span><b>Pago en línea</b><small>Tarjeta de crédito, débito o PSE</small></span></label><label className={styles.payment}><input type="radio" name="payment" /><PackageCheck size={19} /><span><b>Transferencia bancaria</b><small>Instrucciones al confirmar</small></span></label><button><LockKeyhole size={18} />Confirmar pedido</button><small className={styles.secure}><ShieldCheck size={15} />Tu información está protegida y encriptada.</small></fieldset></aside></form></main>;
}
