import { ChevronRight, Home, Plus, ShoppingCart, Sparkles, Star, Trash2, X } from 'lucide-react';
import { useCompare } from '../context/CompareContext';
import { mockProducts } from '../data/mockProducts';
import styles from './ComparePage.module.css';
const money = (value: number) => new Intl.NumberFormat('es-CO', { style: 'currency', currency: 'COP', maximumFractionDigits: 0 }).format(value);
const labels = [{ label: 'Marca', value: (p: any) => p.brand }, { label: 'Categoría', value: (p: any) => p.category }, { label: 'SKU', value: (p: any) => p.sku || '—' }, { label: 'Precio anterior', value: (p: any) => p.previousPrice ? money(p.previousPrice) : '—' }, { label: 'Valoración', value: (p: any) => `${p.rating}/5 (${p.reviewCount})` }, { label: 'Disponibilidad', value: (p: any) => p.stock ? `${p.stock} unidades` : 'Agotado' }, { label: 'Descripción', value: (p: any) => p.shortDescription || '—' }];
export function ComparePage({ onProductClick, onAddToCart }: { onProductClick: (p: any) => void; onAddToCart: (p: any) => void }) {
  const { productIds, removeFromCompare, clearCompare } = useCompare() as any;
  const products = mockProducts.filter((product) => productIds.includes(product.id));
  if (!products.length) return <main className={styles.page}><nav className={styles.breadcrumb} aria-label="Migas de pan"><a href="#inicio"><Home size={16} />Inicio</a><ChevronRight size={15} /><b>Comparar</b></nav><section className={styles.empty}><Sparkles size={52} /><h1>Compara productos</h1><p>Selecciona hasta 4 productos desde la tienda para comparar sus características.</p><a href="#tienda">Explorar tienda</a></section></main>;
  return <main className={styles.page}><nav className={styles.breadcrumb} aria-label="Migas de pan"><a href="#inicio"><Home size={16} />Inicio</a><ChevronRight size={15} /><b>Comparar</b></nav><header className={styles.heading}><div><h1>Comparar productos</h1><p>{products.length} de 4 productos seleccionados</p></div><button type="button" onClick={clearCompare}><Trash2 size={16} />Limpiar comparación</button></header><div className={styles.scroller}><section className={styles.table} style={{ gridTemplateColumns: `185px repeat(${products.length}, minmax(220px, 1fr))` }}><div className={styles.label}>Producto</div>{products.map((product) => <article className={styles.product} key={product.id}><button className={styles.remove} type="button" aria-label={`Quitar ${product.name}`} onClick={() => removeFromCompare(product.id)}><X size={17} /></button><button className={styles.visual} type="button" onClick={() => onProductClick(product)}><img src={product.image} alt={product.name} /><b>{product.name}</b></button></article>)}{labels.map(({ label, value }) => <><div className={styles.label} key={`${label}-label`}>{label}</div>{products.map((product) => <div className={label === 'Descripción' ? styles.description : styles.value} key={`${label}-${product.id}`}>{label === 'Valoración' && <span className={styles.stars}>{Array.from({ length: 5 }, (_, index) => <Star key={index} size={13} fill={index < Math.round(product.rating) ? 'currentColor' : 'none'} />)}</span>}{value(product)}</div>)}</>)}<div className={styles.label}>Acción</div>{products.map((product) => <button className={styles.add} key={`add-${product.id}`} type="button" disabled={!product.stock} onClick={() => onAddToCart(product)}><ShoppingCart size={17} />Agregar al carrito</button>)}</section></div>{products.length < 4 && <a className={styles.addMore} href="#tienda"><Plus size={18} />Agregar otro producto</a>}</main>;
}
