import { useEffect, useMemo, useState } from 'react';
import { Check, ImagePlus, Plus, Search, Star, Trash2, X } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import styles from './AdminProductsPage.module.css';
import modalStyles from './AdminProductsModal.module.css';
import formStyles from './ProductFormDialog.module.css';
import offerStyles from './ProductFormOffer.module.css';
import inventoryStyles from './ProductFormInventory.module.css';

const MAX_ADDITIONAL_IMAGES = 4;
const empty = { name: '', sku: '', slug: '', categoryName: '', brandName: '', basePrice: '', compareAtPrice: '', offerStartsAt: '', offerEndsAt: '', physicalQuantity: 0, weightGrams: '', lengthCm: '', widthCm: '', heightCm: '', warranty: '', condition: '', tags: [], relatedProductIds: [], seoTitle: '', seoDescription: '', shortDescription: '', description: '', imageUrls: [], specifications: {}, variants: [], status: 'ACTIVE', isFeatured: false };
const dateValue = (value) => value ? new Date(value).toISOString().slice(0, 16) : '';
const localDateTimeValue = (value = new Date()) => new Date(value.getTime() - value.getTimezoneOffset() * 60000).toISOString().slice(0, 16);
const toSpecifications = (specifications) => Object.entries(specifications || {}).map(([key, value]) => ({ key, value: String(value) }));
const serializeSpecifications = (specifications) => Object.fromEntries(specifications.filter(({ key, value }) => key.trim() && value.trim()).map(({ key, value }) => [key.trim(), value.trim()]));
const attributesToText = (attributes) => Object.entries(attributes || {}).map(([key, value]) => `${key}: ${value}`).join('\n');
const textToAttributes = (value) => Object.fromEntries(value.split('\n').map((line) => line.split(/:(.*)/)).filter(([key, detail]) => key?.trim() && detail?.trim()).map(([key, detail]) => [key.trim(), detail.trim()]));
const nullableNumber = (value) => value === '' || value == null ? null : Number(value);
const optionalText = (value) => value?.trim() || undefined;
const variantForm = (variant) => ({ ...variant, attributesText: attributesToText(variant.attributes) });

function ImagePreview({ url, alt, prominent = false }) {
  const [failed, setFailed] = useState(false);
  useEffect(() => setFailed(false), [url]);
  return <div className={`${formStyles.preview} ${prominent ? formStyles.mainPreview : ''} ${failed ? formStyles.failedPreview : ''}`}>
    {url && !failed ? <img src={url} alt={alt} onError={() => setFailed(true)} /> : <><ImagePlus size={prominent ? 34 : 22} /><span>{failed ? 'No se pudo cargar la imagen' : prominent ? 'Aún no has agregado una imagen' : 'Sin imagen'}</span></>}
  </div>;
}

export function ProductFormDialog({ product, onCancel, onSaved, onFailed }) {
  const { request } = useAuth();
  const initialImages = product?.imageUrls || (product?.imageUrl ? [product.imageUrl] : []);
  const [values, setValues] = useState(() => ({ ...empty, ...product, relatedProductIds: product?.relatedProductIds || [], categoryName: product?.category || '', brandName: product?.brand || '', offerStartsAt: dateValue(product?.offerStartsAt), offerEndsAt: dateValue(product?.offerEndsAt) }));
  const [mainImage, setMainImage] = useState(() => initialImages[0] || '');
  const [additionalImages, setAdditionalImages] = useState(() => initialImages.slice(1, MAX_ADDITIONAL_IMAGES + 1));
  const [specifications, setSpecifications] = useState(() => toSpecifications(product?.specifications));
  const [variants, setVariants] = useState(() => (product?.variants || []).map(variantForm));
  const [tagsText, setTagsText] = useState(() => (product?.tags || []).join(', '));
  const [hasOffer, setHasOffer] = useState(() => Boolean(product?.compareAtPrice || product?.offerStartsAt || product?.offerEndsAt));
  const [error, setError] = useState('');
  const [saving, setSaving] = useState(false);
  const [catalogProducts, setCatalogProducts] = useState([]);
  const [relatedQuery, setRelatedQuery] = useState('');
  useEffect(() => { const previous = document.body.style.overflow; document.body.style.overflow = 'hidden'; return () => { document.body.style.overflow = previous; }; }, []);
  useEffect(() => { let active = true; request('/admin/products?includeArchived=true').then((data) => { if (active) setCatalogProducts(data.products || []); }).catch(() => {}); return () => { active = false; }; }, [request]);

  const update = (key, value) => setValues((current) => ({ ...current, [key]: value }));
  const toggleRelated = (id) => setValues((current) => ({ ...current, relatedProductIds: current.relatedProductIds.includes(id) ? current.relatedProductIds.filter((item) => item !== id) : current.relatedProductIds.length < 4 ? [...current.relatedProductIds, id] : current.relatedProductIds }));
  const updateAdditional = (index, url) => setAdditionalImages((current) => current.map((item, itemIndex) => itemIndex === index ? url : item));
  const addAdditional = () => setAdditionalImages((current) => current.length < MAX_ADDITIONAL_IMAGES ? [...current, ''] : current);
  const removeAdditional = (index) => setAdditionalImages((current) => current.filter((_, itemIndex) => itemIndex !== index));
  const updateSpecification = (index, field, value) => setSpecifications((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, [field]: value } : item));
  const addSpecification = () => setSpecifications((current) => current.length < 20 ? [...current, { key: '', value: '' }] : current);
  const removeSpecification = (index) => setSpecifications((current) => current.filter((_, itemIndex) => itemIndex !== index));
  const updateVariant = (index, field, value) => setVariants((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, [field]: value } : item));
  const addVariant = () => setVariants((current) => current.length < 20 ? [...current, { sku: '', attributesText: '', priceOverride: '', physicalQuantity: 0 }] : current);
  const removeVariant = (index) => setVariants((current) => current.filter((_, itemIndex) => itemIndex !== index));
  const useAsMain = (index) => { const selected = additionalImages[index]; setAdditionalImages((current) => [...(mainImage ? [mainImage] : []), ...current.filter((_, itemIndex) => itemIndex !== index)]); setMainImage(selected); };
  const variantStock = useMemo(() => variants.reduce((total, variant) => total + (Number(variant.physicalQuantity) || 0), 0), [variants]);
  const totalStock = (Number(values.physicalQuantity) || 0) + variantStock;
  const isEditing = Boolean(values.id);
  const selectedRelatedProducts = values.relatedProductIds.map((id) => catalogProducts.find((item) => item.id === id)).filter(Boolean);
  const normalizedRelatedQuery = relatedQuery.trim().toLocaleLowerCase();
  const relatedSearchResults = normalizedRelatedQuery ? catalogProducts.filter((item) => item.id !== values.id && item.status !== 'ARCHIVED' && !values.relatedProductIds.includes(item.id) && `${item.name} ${item.sku} ${item.category}`.toLocaleLowerCase().includes(normalizedRelatedQuery)) : [];
  // Las ofertas existentes deben poder corregirse, incluso si sus fechas ya pasaron.
  // La restricción de fecha actual se aplica únicamente al crear un producto nuevo.
  const offerStartMinimum = isEditing ? undefined : localDateTimeValue();
  const offerEndMinimum = isEditing ? undefined : values.offerStartsAt && values.offerStartsAt > offerStartMinimum ? values.offerStartsAt : offerStartMinimum;

  const submit = async (event) => {
    event.preventDefault(); setError('');
    if (!values.categoryName.trim()) return setError('Indica una categoría.');
    if (!mainImage.trim()) return setError('La imagen principal es obligatoria.');
    if (hasOffer && (!values.compareAtPrice || !values.offerStartsAt || !values.offerEndsAt)) return setError('Completa precio anterior, inicio y fin para activar la oferta.');
    if (hasOffer && Number(values.compareAtPrice) <= Number(values.basePrice)) return setError('El precio anterior debe ser mayor al precio de venta.');
    setSaving(true);
    try {
      const payload = { ...values, categoryName: values.categoryName.trim(), brandName: values.brandName.trim(), slug: values.slug.trim(), condition: values.condition || null, seoTitle: optionalText(values.seoTitle), seoDescription: optionalText(values.seoDescription), shortDescription: optionalText(values.shortDescription), description: optionalText(values.description), warranty: optionalText(values.warranty), basePrice: Number(values.basePrice), compareAtPrice: hasOffer ? Number(values.compareAtPrice) : null, physicalQuantity: Number(values.physicalQuantity), weightGrams: nullableNumber(values.weightGrams), lengthCm: nullableNumber(values.lengthCm), widthCm: nullableNumber(values.widthCm), heightCm: nullableNumber(values.heightCm), offerStartsAt: hasOffer ? new Date(values.offerStartsAt).toISOString() : null, offerEndsAt: hasOffer ? new Date(values.offerEndsAt).toISOString() : null, imageUrls: [mainImage, ...additionalImages].map((url) => url.trim()).filter(Boolean), specifications: serializeSpecifications(specifications), tags: [...new Set(tagsText.split(',').map((tag) => tag.trim()).filter(Boolean))], variants: variants.map((variant) => ({ ...(variant.id ? { id: variant.id } : {}), sku: variant.sku.trim(), attributes: textToAttributes(variant.attributesText), priceOverride: nullableNumber(variant.priceOverride), physicalQuantity: Number(variant.physicalQuantity) })) };
      const data = await request(values.id ? `/admin/products/${values.id}` : '/admin/products', { method: values.id ? 'PUT' : 'POST', body: JSON.stringify(payload) });
      onSaved(data.product, values.id ? 'updated' : 'created');
    } catch (requestError) { setError(requestError.message); onFailed?.(requestError.message); } finally { setSaving(false); }
  };

  return <div className={`${styles.backdrop} ${modalStyles.backdrop}`} role="presentation"><section className={`${styles.dialog} ${modalStyles.dialog} ${formStyles.dialog}`} role="dialog" aria-modal="true" aria-labelledby="product-form-title"><header><div><p>Administración de catálogo</p><h2 id="product-form-title">{values.id ? 'Editar producto' : 'Nuevo producto'}</h2></div><button type="button" aria-label="Cerrar" onClick={onCancel}><X /></button></header><form onSubmit={submit}>{error && <p className={styles.error}>{error}</p>}
    <section className={formStyles.section}><h3>Información general</h3><div className={styles.formGrid}><label>Nombre<input required value={values.name} onChange={(event) => update('name', event.target.value)} /></label><label>SKU o código interno<input required value={values.sku} onChange={(event) => update('sku', event.target.value)} placeholder="Ej. FEF-LAP-001" /></label><label>Categoría<input required value={values.categoryName} onChange={(event) => update('categoryName', event.target.value)} placeholder="Ej. Computadores" /></label><label>Marca<input value={values.brandName} onChange={(event) => update('brandName', event.target.value)} placeholder="Ej. Lenovo" /></label><label className={styles.full}>Condición<select value={values.condition || ''} onChange={(event) => update('condition', event.target.value)}><option value="">No especificada</option><option value="NEW">Nuevo</option><option value="REFURBISHED">Reacondicionado</option><option value="USED">Usado</option></select></label></div></section>
    <section className={formStyles.section}><h3>Contenido del catálogo</h3><div className={styles.formGrid}><label className={styles.full}>Descripción corta<textarea maxLength="500" value={values.shortDescription || ''} onChange={(event) => update('shortDescription', event.target.value)} placeholder="Resumen breve para tarjetas y catálogo." /></label><label className={styles.full}>Descripción completa<textarea rows="4" value={values.description || ''} onChange={(event) => update('description', event.target.value)} placeholder="Describe beneficios, compatibilidad y contenido incluido." /></label></div></section>
    <section className={formStyles.section}><h3>Imágenes del producto</h3><p>Agrega una portada obligatoria y, si lo necesitas, hasta cuatro imágenes secundarias para la galería.</p><div className={formStyles.imagesLayout}><article className={formStyles.mainImageCard}><div className={formStyles.imageCardHeading}><span><Star size={16} fill="currentColor" /> Imagen principal</span><small>Se mostrará como portada del producto.</small></div><ImagePreview url={mainImage} alt="Vista previa de imagen principal" prominent /><label className={formStyles.urlLabel}>URL de la imagen principal<input required type="url" value={mainImage} onChange={(event) => setMainImage(event.target.value)} placeholder="https://..." /></label><div className={formStyles.mainActions}><button type="button" className={formStyles.textButton} onClick={() => setMainImage('')}>Eliminar</button><span>Al cambiar la URL, reemplazas la imagen.</span></div></article><aside className={formStyles.additionalPanel}><div className={formStyles.additionalHeading}><div><h4>Imágenes adicionales</h4><p>Opcionales · {additionalImages.filter(Boolean).length} de {MAX_ADDITIONAL_IMAGES}</p></div><button className={formStyles.addImage} type="button" disabled={additionalImages.length >= MAX_ADDITIONAL_IMAGES} onClick={addAdditional}><ImagePlus size={16} /> Agregar imagen</button></div><div className={formStyles.additionalGrid}>{additionalImages.map((url, index) => <article className={formStyles.additionalCard} key={`${index}-${url}`}><ImagePreview url={url} alt={`Vista previa adicional ${index + 1}`} /><label>URL<input type="url" value={url} onChange={(event) => updateAdditional(index, event.target.value)} placeholder="https://..." /></label><div className={formStyles.additionalActions}><button type="button" onClick={() => useAsMain(index)} disabled={!url.trim()}><Star size={14} /> Principal</button><button type="button" onClick={() => removeAdditional(index)} aria-label={`Eliminar imagen adicional ${index + 1}`}><Trash2 size={15} /> Eliminar</button></div></article>)}<button className={formStyles.emptyAdditional} type="button" disabled={additionalImages.length >= MAX_ADDITIONAL_IMAGES} onClick={addAdditional}><ImagePlus size={22} /><span>Agregar imagen</span></button></div></aside></div></section>
    <section className={formStyles.section}><h3>Precio y oferta</h3><div className={offerStyles.pricingLayout}><label className={offerStyles.salePrice}>Precio de venta<span className={offerStyles.currency}>COP</span><input type="number" min="0" required value={values.basePrice} onChange={(event) => update('basePrice', event.target.value)} /></label><label className={formStyles.offerToggle}><input type="checkbox" checked={hasOffer} onChange={(event) => setHasOffer(event.target.checked)} /><span><b>Oferta por tiempo limitado</b><small>Configura un descuento con fecha de inicio y finalización.</small></span></label></div>{hasOffer && <div className={offerStyles.offerPanel}><div className={offerStyles.offerPanelHeading}><div><b>Configuración de la oferta</b><small>El precio anterior debe ser superior al precio de venta.</small></div><span>Oferta activa</span></div><label className={offerStyles.previousPrice}>Precio anterior<span className={offerStyles.currency}>COP</span><input type="number" min="0" required value={values.compareAtPrice ?? ''} onChange={(event) => update('compareAtPrice', event.target.value)} /></label><div className={offerStyles.offerDates}><label>Inicio de la oferta<input type="datetime-local" required min={offerStartMinimum} value={values.offerStartsAt} onChange={(event) => update('offerStartsAt', event.target.value)} /></label><label>Finalización de la oferta<input type="datetime-local" required min={offerEndMinimum} value={values.offerEndsAt} onChange={(event) => update('offerEndsAt', event.target.value)} /></label></div></div>}</section>
    <section className={formStyles.section}><div className={formStyles.variantEditor}><div className={formStyles.specificationHeading}><div><h3>Variantes</h3><p>Úsalas para color, capacidad, memoria u otra versión con SKU, precio o inventario propio.</p></div><button type="button" onClick={addVariant} disabled={variants.length >= 20}><Plus size={16} /> Agregar variante</button></div>{variants.length ? <div className={formStyles.variantList}>{variants.map((variant, index) => <article className={formStyles.variantCard} key={variant.id || index}><div className={formStyles.variantHeading}><b>Variante {index + 1}</b><button type="button" onClick={() => removeVariant(index)}><Trash2 size={16} /> Eliminar</button></div><div className={styles.formGrid}><label>SKU de variante<input required value={variant.sku} onChange={(event) => updateVariant(index, 'sku', event.target.value)} placeholder="Ej. FEF-LAP-001-16GB" /></label><label>Precio especial<input type="number" min="0" value={variant.priceOverride ?? ''} onChange={(event) => updateVariant(index, 'priceOverride', event.target.value)} placeholder="Opcional" /></label><label className={styles.full}>Atributos<textarea rows="2" value={variant.attributesText} onChange={(event) => updateVariant(index, 'attributesText', event.target.value)} placeholder={'Color: Negro\nMemoria RAM: 16 GB'} /><small>Una característica por línea, con formato “Nombre: valor”.</small></label><label>Inventario de variante<input type="number" min="0" required value={variant.physicalQuantity} onChange={(event) => updateVariant(index, 'physicalQuantity', event.target.value)} /></label></div></article>)}</div> : <button type="button" className={formStyles.emptySpecification} onClick={addVariant}><Plus size={20} /><span>Agregar la primera variante</span></button>}</div></section>
    <section className={formStyles.section}><h3>Inventario y envío</h3><p className={formStyles.inventorySummary}>Inventario base: <b>{Number(values.physicalQuantity) || 0}</b> · Variantes: <b>{variantStock}</b> · Total disponible: <b>{totalStock}</b></p><div className={inventoryStyles.grid}><label className={`${inventoryStyles.field} ${inventoryStyles.stockField}`}>Inventario base<span>Unidades disponibles sin variantes.</span><input type="number" min="0" required value={values.physicalQuantity} onChange={(event) => update('physicalQuantity', event.target.value)} /></label><label className={`${inventoryStyles.field} ${inventoryStyles.shippingField}`}>Peso<span>En gramos; opcional para el envío.</span><input type="number" min="0" value={values.weightGrams ?? ''} onChange={(event) => update('weightGrams', event.target.value)} placeholder="g" /></label><label className={`${inventoryStyles.field} ${inventoryStyles.shippingField}`}>Largo<span>Dimensión del empaque en centímetros.</span><input type="number" min="0" value={values.lengthCm ?? ''} onChange={(event) => update('lengthCm', event.target.value)} placeholder="cm" /></label><label className={`${inventoryStyles.field} ${inventoryStyles.shippingField}`}>Ancho<span>Dimensión del empaque en centímetros.</span><input type="number" min="0" value={values.widthCm ?? ''} onChange={(event) => update('widthCm', event.target.value)} placeholder="cm" /></label><label className={`${inventoryStyles.field} ${inventoryStyles.shippingField}`}>Alto<span>Dimensión del empaque en centímetros.</span><input type="number" min="0" value={values.heightCm ?? ''} onChange={(event) => update('heightCm', event.target.value)} placeholder="cm" /></label></div></section>
    <section className={formStyles.section}><div className={formStyles.specificationEditor}><div className={formStyles.specificationHeading}><div><h3>Especificaciones técnicas</h3><p>Agrega únicamente los datos que ayudan a comparar este producto.</p></div><button type="button" onClick={addSpecification} disabled={specifications.length >= 20}><Plus size={16} /> Agregar especificación</button></div>{specifications.length ? <div className={formStyles.specificationRows}>{specifications.map((specification, index) => <div className={formStyles.specificationRow} key={index}><input value={specification.key} maxLength="100" onChange={(event) => updateSpecification(index, 'key', event.target.value)} placeholder="Característica (ej. Memoria RAM)" /><input value={specification.value} maxLength="1000" onChange={(event) => updateSpecification(index, 'value', event.target.value)} placeholder="Valor (ej. 16 GB)" /><button type="button" onClick={() => removeSpecification(index)} aria-label="Eliminar especificación"><Trash2 size={16} /></button></div>)}</div> : <button type="button" className={formStyles.emptySpecification} onClick={addSpecification}><Plus size={20} /><span>Agregar la primera especificación</span></button>}</div></section>
    <section className={formStyles.section}><h3>Información comercial</h3><div className={styles.formGrid}><label>Garantía<input maxLength="255" value={values.warranty || ''} onChange={(event) => update('warranty', event.target.value)} placeholder="Ej. 12 meses directamente con fabricante" /></label><label className={styles.full}>Etiquetas<input value={tagsText} onChange={(event) => setTagsText(event.target.value)} placeholder="Ej. gaming, portátil, oficina" /><small>Sepáralas por comas. Servirán para filtros o campañas futuras.</small></label></div></section>
    <section className={formStyles.section}><div className={formStyles.relatedEditor}><div className={formStyles.relatedHeading}><div><h3>Productos relacionados</h3><p>Selecciona hasta cuatro productos para mostrarlos en esta ficha. Si no eliges ninguno, se usarán sugerencias automáticas.</p></div><span className={formStyles.relatedCount}>{values.relatedProductIds.length} de 4 seleccionados</span></div><div className={formStyles.relatedSelectedArea}><div className={formStyles.relatedSubheading}><b>Seleccionados</b><span>{values.relatedProductIds.length ? 'Visibles al guardar' : 'Aún no has seleccionado productos'}</span></div>{selectedRelatedProducts.length ? <div className={formStyles.relatedList}>{selectedRelatedProducts.map((item) => <article className={`${formStyles.relatedCard} ${formStyles.relatedSelected}`} key={item.id}><span className={formStyles.relatedMark} aria-hidden="true"><Check size={14} /></span><span className={formStyles.relatedProduct}><b>{item.name}</b><small>{item.category} · {item.sku}</small></span><button type="button" className={formStyles.relatedRemove} onClick={() => toggleRelated(item.id)} aria-label={`Quitar ${item.name} de productos relacionados`}><X size={16} /></button></article>)}</div> : <p className={formStyles.relatedEmpty}>Los productos que selecciones aparecerán aquí.</p>}</div><label className={formStyles.relatedSearch}>Buscar producto<span className={formStyles.searchField}><Search size={17} aria-hidden="true" /><input type="search" value={relatedQuery} onChange={(event) => setRelatedQuery(event.target.value)} placeholder="Nombre, SKU o categoría" /></span></label>{normalizedRelatedQuery && <div className={formStyles.relatedResults} aria-live="polite"><div className={formStyles.relatedSubheading}><b>Resultados de búsqueda</b><span>{relatedSearchResults.length} encontrados</span></div>{relatedSearchResults.length ? <div className={formStyles.relatedList}>{relatedSearchResults.map((item) => <button type="button" className={formStyles.relatedCard} key={item.id} disabled={values.relatedProductIds.length >= 4} onClick={() => toggleRelated(item.id)}><span className={formStyles.relatedProduct}><b>{item.name}</b><small>{item.category} · {item.sku}</small></span><span className={formStyles.relatedAdd}>Agregar</span></button>)}</div> : <p className={formStyles.relatedEmpty}>No se encontraron productos.</p>}</div>}</div></section>
    <section className={formStyles.section}><h3>Visibilidad</h3><div className={formStyles.visibility}><label>Estado<select value={values.status} onChange={(event) => update('status', event.target.value)}><option value="ACTIVE">Activo</option><option value="DRAFT">Borrador</option><option value="INACTIVE">Inactivo</option></select></label><label className={formStyles.featured}><input type="checkbox" checked={Boolean(values.isFeatured)} onChange={(event) => update('isFeatured', event.target.checked)} /><span><b>Mostrar en productos destacados</b><small>Se verá en la sección principal de la tienda.</small></span></label></div></section>
    <section className={formStyles.section}><h3>SEO y publicación</h3><div className={styles.formGrid}><label className={styles.full}>URL amigable<input value={values.slug || ''} onChange={(event) => update('slug', event.target.value)} placeholder="Se genera automáticamente desde el nombre si lo dejas vacío" /><small>Solo letras, números y guiones; se ajustará automáticamente si ya existe.</small></label><label className={styles.full}>Título para buscadores<input maxLength="255" value={values.seoTitle || ''} onChange={(event) => update('seoTitle', event.target.value)} placeholder="Opcional; si lo dejas vacío se usará el nombre del producto." /></label><label className={styles.full}>Descripción para buscadores<textarea rows="2" maxLength="500" value={values.seoDescription || ''} onChange={(event) => update('seoDescription', event.target.value)} placeholder="Opcional; resumen para resultados de búsqueda." /></label></div></section>
    <footer><button type="button" className={styles.secondary} onClick={onCancel}>Cancelar</button><button disabled={saving}>{saving ? 'Guardando…' : 'Guardar producto'}</button></footer>
  </form></section></div>;
}
